import { useState } from 'react';
import { ArrowRight, ArrowUpRight, BarChart3, Check, Menu, Phone, PhoneCall, Search, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import './frontend-landing-preview.css';

const cards = [
  { icon: Search, number: '01', title: 'Find the right people.', text: 'Turn a simple search into a clean, ready-to-call lead list.', color: 'blue' },
  { icon: PhoneCall, number: '02', title: 'Make every call count.', text: 'Call, take notes and plan your next follow-up in one place.', color: 'green' },
  { icon: BarChart3, number: '03', title: 'See what is working.', text: 'Track activity, talk time and outcomes without spreadsheet work.', color: 'orange' },
];

export default function FrontendLandingPreview() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeCard, setActiveCard] = useState(0);
  const go = (id: string) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenuOpen(false); };
  return <div className="landing-preview">
    <nav className="landing-nav"><button className="landing-brand" onClick={() => go('home-preview')}><span className="landing-mark"><PhoneCall size={18} /></span><span>Jento<span>AI</span><small>Calling workspace</small></span></button><div className={`landing-links ${menuOpen ? 'open' : ''}`}><button onClick={() => go('workflow')}>How it works</button><button onClick={() => go('features')}>Features</button><button onClick={() => go('results')}>Results</button><button className="nav-mobile-close" onClick={() => setMenuOpen(false)}><X size={19} /></button></div><div className="landing-nav-actions"><Link to="/login" className="text-button">Sign in</Link><Link to="/signup" className="nav-cta">Get started <ArrowUpRight size={15} /></Link></div><button className="landing-menu" aria-label="Open menu" onClick={() => setMenuOpen(true)}><Menu size={22} /></button></nav>
    <main id="home-preview">
      <section className="landing-hero"><div className="hero-copy"><div className="landing-eyebrow"><span /> JENTO AI / CALLING</div><h1>More conversations.<br /><em>Less busywork.</em></h1><p>Find better leads, call with confidence and keep your whole outreach team moving from one clear workspace.</p><div className="hero-actions"><Link to="/signup" className="landing-primary">Start calling <ArrowRight size={17} /></Link><button className="landing-secondary" onClick={() => go('workflow')}>See how it works <ArrowRight size={16} /></button></div><div className="hero-proof"><div className="proof-faces"><span>AM</span><span>RK</span><span>JL</span></div><div><strong>Built for teams that follow up.</strong><small>Lead enrichment + calling in one place</small></div></div></div><div className="hero-visual"><div className="visual-top"><span className="tiny-dot" /> Live workspace <span className="visual-time">Today, 10:42 AM</span></div><div className="visual-head"><div><small>OUTREACH OVERVIEW</small><strong>Good momentum.</strong></div><span className="visual-score">+24.8%</span></div><div className="visual-chart"><div className="chart-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="hero-bars">{[38,58,47,76,66,91,80].map((height, i) => <div className="hero-bar-group" key={i}><i style={{ height: `${height}%` }} /><b style={{ height: `${height * .62}%` }} /><small>{['M','T','W','T','F','S','S'][i]}</small></div>)}</div></div><div className="visual-bottom"><div><span className="mini-icon blue"><Users size={14} /></span><span><small>Ready to call</small><strong>248 leads</strong></span></div><div><span className="mini-icon orange"><Phone size={14} /></span><span><small>Calls today</small><strong>86 calls</strong></span></div></div><div className="visual-float"><Check size={14} /> Enrichment complete</div></div></section>
      <section className="logo-strip"><span>One workspace for the work behind every good conversation.</span><div><b>LEAD DATA</b><b>OUTREACH</b><b>CALLING</b><b>INSIGHTS</b></div></section>
      <section className="landing-section" id="workflow"><div className="section-intro"><div><div className="landing-eyebrow"><span /> A clearer way to work</div><h2>Your team already knows<br /><em>how to sell.</em></h2></div><p>Jento brings the pieces together so your people spend less time preparing and more time having useful conversations.</p></div><div className="steps"><div className="step active"><span>01</span><strong>Build your list</strong><p>Search and enrich prospects that fit your ideal customer.</p><ArrowRight size={18} /></div><div className="step"><span>02</span><strong>Start a conversation</strong><p>Open the dialer, call from one place and keep context close.</p><ArrowRight size={18} /></div><div className="step"><span>03</span><strong>Keep the momentum</strong><p>Know what happened and take the next best action.</p><ArrowRight size={18} /></div></div></section>
      <section className="landing-section feature-section" id="features"><div className="section-intro compact"><div><div className="landing-eyebrow"><span /> Everything in rhythm</div><h2>Tools that feel<br /><em>easy to use.</em></h2></div><p>Small details add up: clean data, thoughtful calling tools and a dashboard that tells the truth quickly.</p></div><div className="feature-grid">{cards.map(({ icon: Icon, number, title, text, color }, i) => <button key={title} className={`feature-card ${color} ${activeCard === i ? 'selected' : ''}`} onClick={() => setActiveCard(i)}><div className="feature-icon"><Icon size={27} /></div><span className="feature-number">{number} / FEATURE</span><h3>{title}</h3><p>{text}</p><span className="feature-link">Explore feature <ArrowUpRight size={16} /></span></button>)}</div></section>
      <section className="result-section" id="results"><div className="result-copy"><div className="landing-eyebrow"><span /> The calm behind the numbers</div><h2>When the workflow<br /><em>gets out of the way.</em></h2><p>Your team gets a sharper view of the day: who to call, what to say and what to do next.</p><button className="landing-secondary light" onClick={() => go('start')}>Explore the workspace <ArrowRight size={17} /></button></div><div className="result-stats"><div><strong>70%</strong><span>less manual prep</span></div><div><strong>100+</strong><span>hours back each month</span></div><div><strong>1</strong><span>workspace for your team</span></div></div></section>
      <section className="start-section" id="start"><div><div className="landing-eyebrow"><span /> Ready when you are</div><h2>Make your next<br /><em>call count.</em></h2><p>Start with a clean workspace for your first campaign.</p></div><Link to="/signup" className="landing-primary white">Start your free workspace <ArrowRight size={17} /></Link></section>
    </main><footer className="landing-footer"><span>Jento<span>AI</span> / Calling</span><span>Lead enrichment · Outreach · Growth</span></footer>
  </div>;
}
